name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            postgres: 17
          - ruby: 2.7
            postgres: 9.6
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
      - run: |
          createdb pgsync_test1
          createdb pgsync_test2
          createdb pgsync_test3
      - run: bundle exec rake test
